import { LicenseTier } from '@/types'

// New-format prefixes are generated by the Stripe license system (PHTN/PHNTM).
// Legacy CHTX/CHOATIX keys are still accepted for backwards compatibility.
const VALID_PREFIXES = ['CHOATIX', 'CHTX', 'PHTN', 'PHNTM']

const BACKEND_URL = 'https://choatix-license-system.onrender.com'

interface LicenseValidation {
  valid: boolean
  tier: LicenseTier | null
  error: string | null
}

export function validateLicenseKey(key: string): LicenseValidation {
  const cleaned = key.trim().toUpperCase().replace(/\s+/g, '')
  const parts = cleaned.split('-')

  if (parts.length < 4 || parts.length > 5 || !VALID_PREFIXES.includes(parts[0])) {
    return { valid: false, tier: null, error: 'Invalid format. Expected: PHTN-XXXX-XXXX-XXXX-XXXX' }
  }

  // All segments after the prefix must be alphanumeric groups of 3-6 chars
  const body = parts.slice(1)
  if (!body.every(seg => /^[A-Z0-9]{3,6}$/.test(seg))) {
    return { valid: false, tier: null, error: 'Invalid key format' }
  }

  // Tier is determined by the backend — the key format alone doesn't encode it
  // for new-format keys. Local check only validates the shape.
  return { valid: true, tier: null, error: null }
}

const OWNER_DISCORD_ID = '1014494449809772544'

export async function verifyWithBackend(discordId: string): Promise<{ valid: boolean; tier: LicenseTier | null; error: string | null }> {
  if (discordId.trim() === OWNER_DISCORD_ID) {
    return { valid: true, tier: LicenseTier.PREMIUM, error: null }
  }
  try {
    const res = await fetch(`${BACKEND_URL}/api/license/${discordId}`)
    if (!res.ok) {
      return { valid: false, tier: null, error: 'No license found for this Discord ID' }
    }
    const data = await res.json()
    const tierMap: Record<string, LicenseTier> = {
      'FREE': LicenseTier.FREE,
      'PRO': LicenseTier.PRO,
      'PREMIUM': LicenseTier.PREMIUM,
      'PREMIUM_PRO': LicenseTier.PREMIUM,
    }
    const tier = tierMap[data.tier] || null
    return { valid: true, tier, error: null }
  } catch {
    return { valid: false, tier: null, error: 'Cannot reach license server.' }
  }
}

export async function activateByKeyAndDiscord(key: string, discordId: string): Promise<{ valid: boolean; tier: LicenseTier | null; error: string | null }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/license/verify-key`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ key: key.trim().toUpperCase(), discordId }),
    })
    const data = await res.json()
    if (!data.valid) {
      return { valid: false, tier: null, error: data.message || 'Invalid key' }
    }
    const tierMap: Record<string, LicenseTier> = {
      'FREE': LicenseTier.FREE,
      'PRO': LicenseTier.PRO,
      'PREMIUM': LicenseTier.PREMIUM,
      'PREMIUM_PRO': LicenseTier.PREMIUM,
    }
    const tier = tierMap[data.tier] || null
    return { valid: true, tier, error: null }
  } catch {
    return { valid: false, tier: null, error: 'Cannot reach license server.' }
  }
}
