import { Tweak, RollbackEntry, TweakCategory } from '@/types'

interface TweakLog {
  id: string
  tweakId: string
  action: 'apply' | 'revert'
  timestamp: Date
  success: boolean
  error?: string
}

const tweakLog: TweakLog[] = []

function logTweakAction(action: 'apply' | 'revert', tweakId: string, success: boolean, error?: string) {
  tweakLog.push({
    id: `log-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    tweakId, action, timestamp: new Date(), success, error
  })
}

export function getTweakLog() { return [...tweakLog] }

export function createRollbackEntry(tweakId: string): RollbackEntry {
  return {
    id: `rollback-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    tweakId,
    timestamp: new Date(),
    originalValue: ORIGINAL_VALUES[tweakId] ?? 'previous',
    currentValue: NEW_VALUES[tweakId] ?? 'applied',
    reverted: false,
  }
}

export async function revertTweak(entry: RollbackEntry): Promise<boolean> {
  try {
    const result = await window.electronAPI?.restoreTweak(entry.tweakId)
    if (result?.success) {
      logTweakAction('revert', entry.tweakId, true)
      return true
    }
    logTweakAction('revert', entry.tweakId, false, result?.error || 'Restore failed')
    return false
  } catch (error) {
    logTweakAction('revert', entry.tweakId, false, error instanceof Error ? error.message : 'Unknown')
    return false
  }
}

const ORIGINAL_VALUES: Record<string, any> = {
  'sys-high-performance': 'Balanced',
  'sys-enable-game-mode': false,
  'sys-disable-fullscreen-opt': 'enabled',
  'sys-disk-cleanup': 'not run',
  'nv-disable-vsync': 'on',
  'nv-low-latency': 'off',
  'nv-hardware-scheduling': 'off',
  'net-optimize-dns': 'ISP default',
  'net-reduce-congestion': 'default',
  'mouse-disable-acceleration': 'on',
  'storage-ssd-optimization': 'tracking on',
  'storage-trim-optimization': 'auto',
  'windows-explorer-optimization': 'Quick Access',
  'audio-disable-enhancements': 'enabled',
  'audio-usb-optimization': 'selective suspend on',
  'usb-selective-suspend-disable': 'enabled',
  'net-disable-nagle': 'Nagle on',
  'net-disable-power-saving': 'power saving on',
  'sys-enable-ultimate-performance': 'High performance',
  'sys-disable-animations': 'animations on',
  'sys-disable-transparency': 'transparency on',
  'sys-disable-fast-startup': 'fast startup on',
  'sys-disable-sticky-keys': 'sticky keys on',
  'sys-disable-filter-keys': 'filter keys on',
  'sys-disable-toggle-keys': 'toggle keys on',
  'sys-disable-mouse-trails': 'trails on',
  'input-optimize-mouse': 'default',
  'input-optimize-keyboard': 'default',
  'storage-enable-write-cache': 'write cache off',
  'storage-disable-ahci-link-power': 'LPM on',
  'sys-disable-task-view': 'task view on',
  'sys-disable-clipboard-history': 'history on',
  'sys-disable-feedback': 'feedback on',
  'sys-disable-suggested-content': 'suggested on',
  'sys-disable-web-search': 'web search on',
  'debloat-remove-store-bloatware': 'bloatware installed',
  'debloat-remove-onedrive': 'OneDrive active',
  'debloat-clean-temp-files': 'temp files present',
  'debloat-disable-telemetry': 'telemetry on',
  'debloat-remove-news-widget': 'widget active',
  'debloat-disable-web-experience': 'web experience active',
  'debloat-disable-background-access': 'background access on',
  'debloat-disable-store-updates': 'auto-updates on',
  'debloat-remove-xbox-packages': 'xbox packages installed',
  'gpu-max-performance-mode': 'balanced mode',
  'gpu-disable-power-gating': 'power gating on',
  'gpu-optimize-shader-cache': 'default cache',
  'gpu-disable-var-shading': 'VRS on',
  'gpu-set-preferred-mode': 'power saving',
  'gpu-optimize-render-schedule': 'default TDR',
  'gpu-disable-frame-pacing': 'frame pacing on',
  'game-optimize-priority': 'default priority',
  'game-disable-dvr': 'DVR on',
  'game-optimize-scheduler': 'default scheduler',
  'game-disable-game-bar-tips': 'tips on',
  'game-disable-background-recording': 'recording on',
  'game-optimize-fullscreen': 'DWM on',
  'game-disable-hags': 'HAGS on',
  'game-optimize-shader-cache': 'default cache',
  'net-optimize-mtu': 'default MTU',
  'net-disable-network-throttling': 'throttling on',
  'net-optimize-tcp-window': 'default window',
  'net-disable-flow-control': 'flow control on',
  'net-optimize-connection-limits': 'default limits',
  'net-disable-netbios': 'NetBIOS on',
  'audio-optimize-buffer-size': 'default buffer',
  'audio-disable-spatial-sound': 'spatial sound on',
  'audio-set-exclusive-mode': 'shared mode',
  'audio-disable-midi-synth': 'MIDI synth on',
  'sys-set-timer-resolution': 'default timer',
  'sys-disable-power-throttling': 'throttling on',
  'sys-optimize-interrupts': 'default interrupts',
  'sys-disable-spectre-mitigations': 'mitigations on',
  'sys-use-platform-clock': 'HPET default',
  'sys-disable-dynamic-tick': 'dynamic tick on',
  'game-io-priority': 'default I/O priority',
  'game-memory-priority': 'default memory priority',
  'game-disable-game-bar-complete': 'Game Bar active',
  'game-optimize-directx': 'default DirectX',
  'game-optimize-foreground-timer': 'default timer',
  'game-disable-steam-overlay': 'Steam overlay on',
  'game-optimize-cpu-affinity': 'default affinity',
  'game-disable-nagles-algorithm': 'Nagle on',
  'game-optimize-udp-buffer': 'default UDP buffer',
  'game-disable-animations': 'animations on',
  'game-optimize-pagefile': 'auto pagefile',
  'game-disable-powersaving-gpu': 'GPU power saving on',
  'storage-optimize-defrag': 'no schedule',
  'storage-set-io-priority': 'default I/O priority',
  'storage-disable-indexing': 'indexing on',
  'net-optimize-dns-cache': 'default DNS cache',
  'net-disable-ecns': 'ECN on',
  'net-optimize-rss': 'RSS off',
  'sys-optimize-file-cache': 'default file cache',
  'sys-disable-prefetch': 'prefetch on',
  'sys-optimize-context-menu': '400ms delay',
  'sys-clear-system-cache': 'cache full',
  'sys-optimize-dpc-latency': 'default DPC latency',
  'mouse-optimize-polling': 'default polling',
  'keyboard-optimize-repeat': 'default repeat',
  'input-gaming-mode': 'default input',
  'audio-disable-low-latency': 'low latency on',
  'audio-optimize-sample-rate': 'default sample rate',
  'privacy-disable-ad-id': 'ad ID on',
  'privacy-disable-app-launch': 'app launch tracking on',
  'game-disable-fullscreen-boost': 'fullscreen boost on',
  'game-optimize-network-priority': 'no QoS policy',
  'game-disable-eco-mode': 'Eco Mode on',
  'sys-disable-gamebar': 'GameBar on',
  'sys-disable-vbs': 'VBS on',
  'sys-disable-xbox': 'Xbox services running',
  'sys-disable-mitigations': 'all mitigations on',
  'sys-optimize-fps': 'default FPS settings',
  'sys-optimize-device-affinities': 'default affinities',
  'sys-optimize-msi': 'MSI off',
  'sys-reduce-background': 'background processes active',
  'sys-disable-hibernation': 'hibernation on',
  'sys-enable-modern-memory': 'legacy memory management',
  'sys-disable-services': 'all services running',
  'sys-optimize-storage': 'default storage settings',
  'sys-reduce-boot-timeout': '30s boot timeout',
  'sys-optimize-explorer': 'default Explorer settings',
  'sys-disable-boot-interface': 'boot interface on',
  'sys-optimize-browser-bg': 'browser background active',
  'nv-disable-telemetry': 'NVIDIA telemetry on',
  'nv-optimize-performance': 'default NVIDIA performance',
  'nv-enhance-privacy': 'default NVIDIA privacy',
  'nv-enable-dlss-indicator': 'DLSS indicator off',
  'nv-texture-filtering': 'default texture filtering',
  'net-optimize-performance': 'default network performance',
  'net-disable-lso': 'LSO on',
  'keyboard-disable-filter': 'keyboard filter on',
  'keyboard-usb-power-mgmt': 'USB power management on',
  'privacy-reduce-ads': 'ads tracking on',
  'privacy-optimize-smb': 'default SMB settings',
  'privacy-disable-security-questions': 'security questions on',
  'privacy-harden-security': 'default security settings',
  'privacy-disable-vpn': 'VPN enabled',
  'privacy-disable-ucpd': 'UCPD on',
  'privacy-unlock-eu-privacy': 'EU privacy locked',
  'privacy-redirect-web-searches': 'web searches redirected',
  'privacy-disable-driver-updates': 'auto driver updates on',
  'privacy-disable-vm-support': 'VM support on',
  'sys-disable-tips': 'tips on',
  'sys-disable-lockscreen-spotlight': 'lock screen spotlight on',
  'sys-disable-start-suggestions': 'start suggestions on',
  'sys-disable-error-reporting': 'error reporting on',
  'sys-disable-delivery-optimization': 'delivery optimization on',
  'sys-disable-location': 'location on',
  'sys-disable-find-my-device': 'find my device on',
  'sys-disable-activity-history': 'activity history on',
  'sys-disable-widgets': 'widgets enabled',
  'sys-disable-taskbar-search': 'taskbar search on',
  'sys-disable-cortana': 'Cortana enabled',
  'sys-disable-cloud-clipboard': 'cloud clipboard on',
  'sys-disable-meet-now': 'Meet Now on',
  'sys-disable-people-bar': 'people bar on',
  'sys-disable-search-highlights': 'search highlights on',
  'sys-disable-taskbar-feed': 'taskbar feed on',
  'sys-disable-lockscreen-notifications': 'lock screen notifications on',
  'sys-disable-action-center': 'action center on',
  'sys-disable-scheduled-defrag': 'scheduled defrag on',
  'qol-clean-taskbar': 'default taskbar',
  'qol-classic-photo-viewer': 'modern photo viewer',
  'qol-bypass-win11': 'Windows 11 requirements enforced',
  'qol-disable-disk-quotas': 'disk quotas on',
  'qol-optimize-browsing': 'default browsing settings',
  'qol-disable-browser-hw-accel': 'browser HW accel on',
  'storage-nvme-optimization': 'default NVMe settings',
  'storage-prefetch-manager': 'prefetch manager active',
  'debloat-remove-edge': 'Edge installed',
  'debloat-remove-teams': 'Teams installed',
  'debloat-disable-copilot': 'Copilot enabled',
  'debloat-remove-widgets-deep': 'widgets installed',
  'sys-pause-updates': 'updates active',
  'sys-block-update-restart': 'update restart allowed',
  'sys-defer-feature-updates': 'feature updates immediate',
  'net-block-telemetry-firewall': 'telemetry allowed through firewall',
  'net-block-edge-firewall': 'Edge allowed through firewall',
  'cpu-disable-idle-states': 'CPU idle states on',
  'cpu-max-performance-bios': 'default BIOS settings',
  'gpu-disable-ulps': 'ULPS on',
  'gpu-set-power-limit-max': 'default power limit',
  'sys-realtime-priority-games': 'normal game priority',
  'sys-foreground-boost': 'foreground boost off',
  'game-fortnite-ini-optimize': 'default Fortnite INI',
  'game-valorant-cfg-optimize': 'default Valorant config',
  'game-cs2-cfg-optimize': 'default CS2 config',
  'game-apex-cfg-optimize': 'default Apex config',
  'cpu-core-parking-disable': 'core parking on',
  'sys-cpu-priority': 'default CPU priority',
  'memory-working-set': 'default working set',
}

const NEW_VALUES: Record<string, any> = {
  'sys-high-performance': 'High performance',
  'sys-enable-game-mode': true,
  'sys-disable-fullscreen-opt': 'disabled',
  'sys-disk-cleanup': 'done',
  'nv-disable-vsync': 'off',
  'nv-low-latency': 'ultra',
  'nv-hardware-scheduling': 'on',
  'net-optimize-dns': 'Cloudflare 1.1.1.1',
  'net-reduce-congestion': 'CTCP',
  'mouse-disable-acceleration': 'off',
  'storage-ssd-optimization': 'tracking off',
  'storage-trim-optimization': 'forced',
  'windows-explorer-optimization': 'This PC',
  'audio-disable-enhancements': 'disabled',
  'audio-usb-optimization': 'suspend off',
  'usb-selective-suspend-disable': 'disabled',
  'net-disable-nagle': 'Nagle off',
  'net-disable-power-saving': 'power saving off',
  'sys-enable-ultimate-performance': 'Ultimate Performance',
  'sys-disable-animations': 'animations off',
  'sys-disable-transparency': 'transparency off',
  'sys-disable-fast-startup': 'fast startup off',
  'sys-disable-sticky-keys': 'sticky keys off',
  'sys-disable-filter-keys': 'filter keys off',
  'sys-disable-toggle-keys': 'toggle keys off',
  'sys-disable-mouse-trails': 'trails off',
  'input-optimize-mouse': 'optimized',
  'input-optimize-keyboard': 'optimized',
  'storage-enable-write-cache': 'write cache on',
  'storage-disable-ahci-link-power': 'LPM off',
  'sys-disable-task-view': 'task view off',
  'sys-disable-clipboard-history': 'history off',
  'sys-disable-feedback': 'feedback off',
  'sys-disable-suggested-content': 'suggested off',
  'sys-disable-web-search': 'web search off',
  'debloat-remove-store-bloatware': 'bloatware removed',
  'debloat-remove-onedrive': 'OneDrive disabled',
  'debloat-clean-temp-files': 'temp cleaned',
  'debloat-disable-telemetry': 'telemetry off',
  'debloat-remove-news-widget': 'widget disabled',
  'debloat-disable-web-experience': 'web experience off',
  'debloat-disable-background-access': 'background access off',
  'debloat-disable-store-updates': 'auto-updates off',
  'debloat-remove-xbox-packages': 'xbox packages removed',
  'gpu-max-performance-mode': 'max performance',
  'gpu-disable-power-gating': 'power gating off',
  'gpu-optimize-shader-cache': 'optimized cache',
  'gpu-disable-var-shading': 'VRS off',
  'gpu-set-preferred-mode': 'performance mode',
  'gpu-optimize-render-schedule': 'optimized TDR',
  'gpu-disable-frame-pacing': 'frame pacing off',
  'game-optimize-priority': 'high priority',
  'game-disable-dvr': 'DVR off',
  'game-optimize-scheduler': 'optimized scheduler',
  'game-disable-game-bar-tips': 'tips off',
  'game-disable-background-recording': 'recording off',
  'game-optimize-fullscreen': 'exclusive fullscreen',
  'game-disable-hags': 'HAGS off',
  'game-optimize-shader-cache': 'optimized cache',
  'net-optimize-mtu': 'optimized MTU',
  'net-disable-network-throttling': 'throttling off',
  'net-optimize-tcp-window': 'optimized window',
  'net-disable-flow-control': 'flow control off',
  'net-optimize-connection-limits': 'max connections',
  'net-disable-netbios': 'NetBIOS off',
  'audio-optimize-buffer-size': 'optimized buffer',
  'audio-disable-spatial-sound': 'spatial sound off',
  'audio-set-exclusive-mode': 'exclusive mode',
  'audio-disable-midi-synth': 'MIDI synth off',
  'sys-set-timer-resolution': '0.5ms timer',
  'sys-disable-power-throttling': 'throttling off',
  'sys-optimize-interrupts': 'optimized interrupts',
  'sys-disable-spectre-mitigations': 'mitigations off',
  'sys-use-platform-clock': 'platform clock',
  'sys-disable-dynamic-tick': 'dynamic tick off',
  'game-io-priority': 'high I/O priority',
  'game-memory-priority': 'optimized memory',
  'game-disable-game-bar-complete': 'Game Bar disabled',
  'game-optimize-directx': 'optimized DirectX',
  'game-optimize-foreground-timer': '1ms timer',
  'game-disable-steam-overlay': 'Steam overlay off',
  'game-optimize-cpu-affinity': 'optimized affinity',
  'game-disable-nagles-algorithm': 'Nagle off',
  'game-optimize-udp-buffer': 'optimized UDP buffer',
  'game-disable-animations': 'animations off',
  'game-optimize-pagefile': 'fixed pagefile',
  'game-disable-powersaving-gpu': 'GPU max performance',
  'storage-optimize-defrag': 'optimized',
  'storage-set-io-priority': 'high I/O priority',
  'storage-disable-indexing': 'indexing off',
  'net-optimize-dns-cache': 'optimized DNS cache',
  'net-disable-ecns': 'ECN off',
  'net-optimize-rss': 'RSS on',
  'sys-optimize-file-cache': 'optimized file cache',
  'sys-disable-prefetch': 'prefetch off',
  'sys-optimize-context-menu': '50ms delay',
  'sys-clear-system-cache': 'cache cleared',
  'sys-optimize-dpc-latency': 'low DPC latency',
  'mouse-optimize-polling': 'optimized polling',
  'keyboard-optimize-repeat': 'fast repeat',
  'input-gaming-mode': 'zero-delay input',
  'audio-disable-low-latency': 'low latency off',
  'audio-optimize-sample-rate': '48kHz',
  'privacy-disable-ad-id': 'ad ID off',
  'privacy-disable-app-launch': 'app launch tracking off',
  'game-disable-fullscreen-boost': 'fullscreen boost off',
  'game-optimize-network-priority': 'QoS game traffic',
  'game-disable-eco-mode': 'Eco Mode off',
  'sys-disable-gamebar': 'GameBar off',
  'sys-disable-vbs': 'VBS off',
  'sys-disable-xbox': 'Xbox disabled',
  'sys-disable-mitigations': 'all mitigations off',
  'sys-optimize-fps': 'FPS settings optimized',
  'sys-optimize-device-affinities': 'affinities optimized',
  'sys-optimize-msi': 'MSI on',
  'sys-reduce-background': 'background processes minimized',
  'sys-disable-hibernation': 'hibernation off',
  'sys-enable-modern-memory': 'modern memory management enabled',
  'sys-disable-services': 'unnecessary services disabled',
  'sys-optimize-storage': 'storage settings optimized',
  'sys-reduce-boot-timeout': '5s boot timeout',
  'sys-optimize-explorer': 'Explorer optimized',
  'sys-disable-boot-interface': 'boot interface off',
  'sys-optimize-browser-bg': 'browser background minimized',
  'nv-disable-telemetry': 'NVIDIA telemetry off',
  'nv-optimize-performance': 'NVIDIA performance optimized',
  'nv-enhance-privacy': 'NVIDIA privacy enhanced',
  'nv-enable-dlss-indicator': 'DLSS indicator on',
  'nv-texture-filtering': 'texture filtering optimized',
  'net-optimize-performance': 'network performance optimized',
  'net-disable-lso': 'LSO off',
  'keyboard-disable-filter': 'keyboard filter off',
  'keyboard-usb-power-mgmt': 'USB power management off',
  'privacy-reduce-ads': 'ads tracking off',
  'privacy-optimize-smb': 'SMB settings optimized',
  'privacy-disable-security-questions': 'security questions off',
  'privacy-harden-security': 'security hardened',
  'privacy-disable-vpn': 'VPN disabled',
  'privacy-disable-ucpd': 'UCPD off',
  'privacy-unlock-eu-privacy': 'EU privacy unlocked',
  'privacy-redirect-web-searches': 'web searches not redirected',
  'privacy-disable-driver-updates': 'auto driver updates off',
  'privacy-disable-vm-support': 'VM support off',
  'sys-disable-tips': 'tips off',
  'sys-disable-lockscreen-spotlight': 'lock screen spotlight off',
  'sys-disable-start-suggestions': 'start suggestions off',
  'sys-disable-error-reporting': 'error reporting off',
  'sys-disable-delivery-optimization': 'delivery optimization off',
  'sys-disable-location': 'location off',
  'sys-disable-find-my-device': 'find my device off',
  'sys-disable-activity-history': 'activity history off',
  'sys-disable-widgets': 'widgets disabled',
  'sys-disable-taskbar-search': 'taskbar search off',
  'sys-disable-cortana': 'Cortana disabled',
  'sys-disable-cloud-clipboard': 'cloud clipboard off',
  'sys-disable-meet-now': 'Meet Now off',
  'sys-disable-people-bar': 'people bar off',
  'sys-disable-search-highlights': 'search highlights off',
  'sys-disable-taskbar-feed': 'taskbar feed off',
  'sys-disable-lockscreen-notifications': 'lock screen notifications off',
  'sys-disable-action-center': 'action center off',
  'sys-disable-scheduled-defrag': 'scheduled defrag off',
  'qol-clean-taskbar': 'taskbar cleaned',
  'qol-classic-photo-viewer': 'classic photo viewer set',
  'qol-bypass-win11': 'Windows 11 requirements bypassed',
  'qol-disable-disk-quotas': 'disk quotas off',
  'qol-optimize-browsing': 'browsing optimized',
  'qol-disable-browser-hw-accel': 'browser HW accel off',
  'storage-nvme-optimization': 'NVMe optimized',
  'storage-prefetch-manager': 'prefetch manager disabled',
  'debloat-remove-edge': 'Edge removed',
  'debloat-remove-teams': 'Teams removed',
  'debloat-disable-copilot': 'Copilot disabled',
  'debloat-remove-widgets-deep': 'widgets removed',
  'sys-pause-updates': 'updates paused',
  'sys-block-update-restart': 'update restart blocked',
  'sys-defer-feature-updates': 'feature updates deferred',
  'net-block-telemetry-firewall': 'telemetry blocked via firewall',
  'net-block-edge-firewall': 'Edge blocked via firewall',
  'cpu-disable-idle-states': 'CPU idle states off',
  'cpu-max-performance-bios': 'BIOS set to max performance',
  'gpu-disable-ulps': 'ULPS off',
  'gpu-set-power-limit-max': 'power limit maxed',
  'sys-realtime-priority-games': 'realtime game priority',
  'sys-foreground-boost': 'foreground boost on',
  'game-fortnite-ini-optimize': 'Fortnite INI optimized',
  'game-valorant-cfg-optimize': 'Valorant config optimized',
  'game-cs2-cfg-optimize': 'CS2 config optimized',
  'game-apex-cfg-optimize': 'Apex config optimized',
  'cpu-core-parking-disable': 'core parking off',
  'sys-cpu-priority': 'CPU priority optimized',
  'memory-working-set': 'working set optimized',
}
