services:
  - type: web
    name: choatix-license
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: DISCORD_CLIENT_ID
        value: "1520450575831929083"
      - key: DISCORD_CLIENT_SECRET
        value: "ObLYdB6waUtVREgUPI6KZiSVCYaN4FV1"
      - key: DISCORD_REDIRECT_URI
        value: "https://choatix-v2.onrender.com/api/auth/discord/callback"
