const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  minimize: () => ipcRenderer.send("window-minimize"),
  maximize: () => ipcRenderer.send("window-maximize"),
  close: () => ipcRenderer.send("window-close"),
  scanSystem: () => ipcRenderer.invoke("scan-system"),
  advisorScan: () => ipcRenderer.invoke("advisor-scan"),
  setHighPerformance: () => ipcRenderer.invoke("set-high-performance"),
  setGameMode: (enabled) => ipcRenderer.invoke("set-game-mode", enabled),
  getRealtimeStats: () => ipcRenderer.invoke("get-realtime-stats"),
  getDrives: () => ipcRenderer.invoke("get-drives"),
  clearCache: () => ipcRenderer.invoke("clear-cache"),
  openDriverUpdate: () => ipcRenderer.invoke("open-driver-update"),
  scanProcesses: () => ipcRenderer.invoke("scan-processes"),
  optimizeProcesses: (mode) => ipcRenderer.invoke("optimize-processes", mode),
  restoreProcesses: () => ipcRenderer.invoke("restore-processes"),
  detectGames: (executables) => ipcRenderer.invoke("detect-games", executables),
  applyGameTweaks: (tweakIds) => ipcRenderer.invoke("apply-game-tweaks", tweakIds),
  restoreGameTweaks: (tweakIds) => ipcRenderer.invoke("restore-game-tweaks", tweakIds),
  startAutopilot: (games) => ipcRenderer.invoke("start-autopilot", games),
  stopAutopilot: () => ipcRenderer.invoke("stop-autopilot"),
  getAutopilotStatus: () => ipcRenderer.invoke("get-autopilot-status"),
  onAutopilotEvent: (cb) => { const handler = (_e, data) => cb(data); ipcRenderer.on("autopilot-event", handler); return () => ipcRenderer.removeListener("autopilot-event", handler); },
  runBenchmark: () => ipcRenderer.invoke("run-benchmark"),
  getScheduledScans: () => ipcRenderer.invoke("get-scheduled-scans"),
  scheduleScan: (scan) => ipcRenderer.invoke("schedule-scan", scan),
  unscheduleScan: (id) => ipcRenderer.invoke("unschedule-scan", id),
  oneClickOptimize: () => ipcRenderer.invoke("one-click-optimize"),
  checkForUpdates: () => ipcRenderer.invoke("check-for-updates"),
  reportCrash: (data) => ipcRenderer.invoke("report-crash", data),
  exportSettings: () => ipcRenderer.invoke("export-settings"),
  importSettings: (data) => ipcRenderer.invoke("import-settings", data),
  saveSettingsToFile: () => ipcRenderer.invoke("save-settings-to-file"),
  loadSettingsFromFile: () => ipcRenderer.invoke("load-settings-from-file"),
  applyTweak: (tweakId) => ipcRenderer.invoke("apply-tweak", tweakId),
  restoreTweak: (tweakId) => ipcRenderer.invoke("restore-tweak", tweakId),
  restoreAll: () => ipcRenderer.invoke("restore-all"),
  restoreCategory: (category) => ipcRenderer.invoke("restore-category", category),
  isAdmin: () => ipcRenderer.invoke("is-admin"),
  onCrashEvent: (cb) => ipcRenderer.on("crash-event", (_e, data) => cb(data)),
  saveAppState: (state) => ipcRenderer.invoke("save-app-state", state),
  loadAppState: () => ipcRenderer.invoke("load-app-state"),
  sendFeedback: (feedback) => ipcRenderer.invoke("send-feedback", feedback),
  onSaveStateRequest: (cb) => ipcRenderer.on("save-state-request", () => cb()),
  scanBios: () => ipcRenderer.invoke("scan-bios"),
  getNetworkAdapters: () => ipcRenderer.invoke("get-network-adapters"),
  optimizeMtu: (adapterName) => ipcRenderer.invoke("optimize-mtu", adapterName),
  setAdapterProperty: (adapterName, propertyName, value) => ipcRenderer.invoke("set-adapter-property", adapterName, propertyName, value),
  runBufferbloatTest: () => ipcRenderer.invoke("run-bufferbloat-test"),
  getTimerResolution: () => ipcRenderer.invoke("get-timer-resolution"),
  setTimerResolution: (mode) => ipcRenderer.invoke("set-timer-resolution", mode),
  getProcessList: () => ipcRenderer.invoke("get-process-list"),
  setProcessAffinity: (pid, mask) => ipcRenderer.invoke("set-process-affinity", pid, mask),
  diagnoseFps: () => ipcRenderer.invoke("diagnose-fps"),
  findBottleneck: () => ipcRenderer.invoke("find-bottleneck"),
  runStabilityTest: (duration) => ipcRenderer.invoke("run-stability-test", duration),
  scanBloatware: () => ipcRenderer.invoke("scan-bloatware"),
  removeBloatware: (names) => ipcRenderer.invoke("remove-bloatware", names),
  restoreBloatware: (names) => ipcRenderer.invoke("restore-bloatware", names),
  quickAction: (action) => ipcRenderer.invoke("quick-action", action),
  sendUpdateNotification: (data) => ipcRenderer.invoke("send-update-notification", data),
  getFanSensors: () => ipcRenderer.invoke("get-fan-sensors"),
  setFanSpeed: (fanName, speed) => ipcRenderer.invoke("set-fan-speed", { fanName, speed }),
  submitBenchmark: (data) => ipcRenderer.invoke("submit-benchmark", data),
  getLeaderboard: (opts) => ipcRenderer.invoke("get-leaderboard", opts || {}),
  getUserRank: (discordId) => ipcRenderer.invoke("get-user-rank", { discordId }),
  isElectron: true,
});
